name: Reusable Deploy
on: [workflow_call]
jobs:
  deploy:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Output information
        run: echo "Deploying & uploading"