name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
jobs:
  deploy:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    runs-on: ${{matrix.operating-system}}
    steps:
      - name: Download the code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name:
        run: ls
      - name: Output information
        run: echo "Deploying & uploading"